name: Build

on:
  push:
    branches: [ develop ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ develop ]
    tags: [ 'v*.*.*' ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - if: github.ref_type == 'tag'
        name: set package.json version
        run: npm version from-git --git-tag-version=false
      - if: github.ref_type == 'tag'
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
